"use strict";

var IMPACT_LEVEL = {
    LOW: 0,
    MEDIUM: 1,
    HIGH: 2
};

var MALWARE_TYPE = {
    WEB_SHELL: 0,
    VIRUS: 1,
    MALICIOUS_CODE: 2
};

var db = {
    re: [
        { id: 1,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /r0nin/ig },
        { id: 2,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /m0rtix/ig },
        { id: 3,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /upl0ad/ig },
        { id: 4,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /r57shell/ig },
        { id: 5,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /cFaTaLisTiCz_Fx/ig },
        { id: 6,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Tukulesto/ig },
        { id: 7,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /99shell/ig },
        { id: 8,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /shellbot/ig },
        { id: 9,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /phpshell/ig },
        { id: 10,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /void\.ru/ig },
        { id: 11,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /phpremoteview/ig },
        { id: 12,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /directmail/ig },
        { id: 13,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /bash_history/ig },
        { id: 14,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /brute \*force/ig },
        { id: 15,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /multiviews/ig },
        { id: 16,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /cwings/ig },
        { id: 17,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /vandal/ig },
        { id: 18,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /bitchx/ig },
        { id: 19,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /eggdrop/ig },
        { id: 20,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /guardservices/ig },
        { id: 21,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /psybnc/ig },
        { id: 22,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /dalnet/ig },
        { id: 23,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /undernet/ig },
        { id: 24,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /vulnscan/ig },
        { id: 25,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /spymeta/ig },
        { id: 26,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /raslan58/ig },
        { id: 27,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Webshell/ig },
        { id: 28,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /execute command: <input type="text" name="c">/ig },
        { id: 29,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /jsp File browser/ig },
        { id: 30,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /JspWebshell/ig },
        { id: 31,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /PHPShell/ig },
        { id: 32,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /phpRemoteView/ig },
        { id: 33,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /JspSpy/ig },
        { id: 34,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>Mini Php Shell/ig },
        { id: 35,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>r57Shell/ig },
        { id: 36,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Simple CGI backdoor by DK/ig },
        { id: 37,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /JFolder/ig },
        { id: 38,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /NIX REMOTE WEB-SHELL/ig },
        { id: 39,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Execute Shell Command/ig },
        { id: 40,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /PGTools/ig },
        { id: 41,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>PhpShell \d\.\d<\/title>/ig },
        { id: 42,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /cmd\.jsp/ig },
        { id: 43,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /c99shell<\/title>/ig },
        { id: 44,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /- c99shell<\/title><STYLE>/ig },
        { id: 45,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /http:\/\/ccteam\.ru\/releases\//ig },
        { id: 46,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /hackru\.info/ig },
        { id: 47,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Hmilyld/ig },
        { id: 48,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /darkst/ig },
        { id: 49,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>\*  ernealizm  \* <\/title>/ig },
        { id: 50,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /xIXRbE/ig },
        { id: 51,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /MyShell/ig },
        { id: 52,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /fuckjp/ig },
        { id: 53,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /yoco/ig },
        { id: 54,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /backdoor\.jsp/ig },
        { id: 55,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<input type=text name=".CMD" size=45 value=/ig },
        { id: 56,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>ZoRBaCK Connect<\/title>/ig },
        { id: 57,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /hkmjj/ig },
        { id: 58,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>ASPX Shell<\/title>/ig },
        { id: 59,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>.+- WSO.+<\/title>/ig },
        { id: 60,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /hack520/ig },
        { id: 61,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /BloodSword/ig },
        { id: 62,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Jsp File Admin/ig },
        { id: 63,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /lcxMacros/ig },
        { id: 64,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /JFileMan/ig },
        { id: 65,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>Knull Shell<\/title>/ig },
        { id: 66,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>:: www\.h4ckcity\.org :: Coded By 2MzRp & LocalMan ::<\/title>/ig },
        { id: 67,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>JSP Shell<\/title>/ig },
        { id: 68,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /r57shell<\/title>/ig },
        { id: 69,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /jspreverse\.html/ig },
        { id: 70,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /icesword/ig },
        { id: 71,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<form method="POST" action="cfexec\.cfm">/ig },
        { id: 72,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /JSP Backdoor Reverse Shell/ig },
        { id: 73,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /REMVIEW TOOLS/ig },
        { id: 74,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /PHVayv/ig },
        { id: 75,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /JspDo/ig },
        { id: 76,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /NetworkFileManagerPHP/ig },
        { id: 77,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>Stored Procedure Execute<\/title>/ig },
        { id: 78,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /hacker666/ig },
        { id: 79,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /JSP Backdoor/ig },
        { id: 80,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /h4ntu/ig },
        { id: 81,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>SST Sheller !<\/title>/ig },
        { id: 82,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /www\.hmilyld\.cn/ig },
        { id: 83,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /heroes1412/ig },
        { id: 84,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /safe\.yi\.org/ig },
        { id: 85,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>.+Ani-Shell.+<\/title>/ig },
        { id: 86,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /AspRootkit/ig },
        { id: 87,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Persiangig/ig },
        { id: 88,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Webshell/ig },
        { id: 89,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>awen asp\.net webshell<\/title>/ig },
        { id: 90,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /404 infiltrate team/ig },
        { id: 91,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /pwnshell/ig },
        { id: 92,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /websamba/ig },
        { id: 93,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /xakep/ig },
        { id: 94,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /PHP Shell/ig },
        { id: 95,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>SyRiAn Sh3ll /ig },
        { id: 96,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>.+NTDaddy.+<\/title>/ig },
        { id: 97,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>iTSecTeam<\/title>/ig },
        { id: 98,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /PHANTASMA/ig },
        { id: 99,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<title>PHP-Terminal/ig },
        { id: 100,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /jshell/ig },
        { id: 101,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /lpl38/ig },
        { id: 102,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /<FORM METHOD=GET ACTION='cmdjsp\.jsp'>/ig },
        { id: 103,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /jsp web shell/ig },
        { id: 104,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Cod3rZ/ig },
        { id: 105,  type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /visitorTracker_isMob/ig }
    ],
    path: [
        "php-backdoor.php",
        "simple-backdoor.php",
        "cmd.php",
        "phpshell.php",
        "NCC-Shell.php",
        "mysql.php",
        "mysql_tool.php",
        "gfs_sh.php",
        "iMHaPFtp.php",
        "ironshell.php",
        "lamashell.php",
        "load_shell.php",
        "matamu.php",
        "c99_w4cking.php",
        "Crystal.php",
        "ctt_sh.php",
        "cybershell.php",
        "Dx.php",
        "c99_PSych0.php",
        "c99_madnet.php",
        "c99_locus7s.php",
        "c99.php",
        "accept_language.php",
        "rootshell.php",
        "ru24_post_sh.php",
        "zacosmall.php",
        "pws.php",
        "r57.php",
        "r57_iFX.php",
        "r57_kartal.php",
        "r57_Mohajer22.php",
        "pHpINJ.php",
        "PHPJackal.php",
        "PHPRemoteView.php",
        "Private-i3lue.php",
        "PHANTASMA.php",
        "nstview.php",
        "nshell.php",
        "NetworkFileManagerPHP.php",
        "simple_cmd.php",
        "Uploader.php",
        "php-include-w-shell.php",
        "backupsql.php",
        "myshell.php",
        "c99shell.php",
        "c100.php",
        "c100shell.php",
        "locus7s.php",
        "locus.php",
        "safe0ver.php",
        "stresbypass.php",
        "ekin0x.php",
        "liz0zim.php",
        "erne.php",
        "spybypass.php",
        "phpbypass.php",
        "sosyete.php",
        "remview.php",
        "zaco.php",
        "nst.php",
        "heykir.php",
        "simattacker.php",
        "avent.php",
        "fatal.php",
        "dx.php",
        "goonshell.php",
        "safemod.php",
        "unreal.php",
        "w4k.php",
        "winshell.php",
        "mysql2.php",
        "sql.php",
        "jackal.php",
        "dc.php",
        "w4cking.php",
        "x.php",
        "xx.php",
        "xxx.php",
        "w3k.php",
        "h4x.php",
        "h4x0r.php",
        "l33t.php",
        "cod3r.php",
        "cod3rzshell.php",
        "cod3rz.php",
        "locus.php",
        "locu.php",
        "jsback.php",
        "worm.php",
        "simp-worm_sys.p5.php",
        "owned.php",
        "0wn3d.php",
        "perlcmd.cgi",
        "cmd.pl",
        "shell.pl",
        "cmd.cgi",
        "shell.cgi",
        "jsp-reverse.jsp",
        "cmdjsp.jsp",
        "cmd.jsp",
        "cmd_win32.jsp",
        "JspWebshell.jsp",
        "JspWebshell1.2.jsp",
        "shell.jsp",
        "jsp-reverse.jspx",
        "cmdjsp.jspx",
        "cmd.jspx",
        "cmd_win32.jspx",
        "JspWebshell.jspx",
        "JspWebshell1.2.jspx",
        "shell.jspx",
        "browser.jsp",
        "cmd_win32.jsp",
        "CmdServlet",
        "cmdServlet",
        "servlet/CmdServlet",
        "servlet/cmdServlet",
        "ListServlet",
        "UpServlet",
        "up_win32.jsp",
        "cmd.asp",
        "cmdasp.aspx",
        "cmdasp.asp",
        "cmd-asp-5.1.asp",
        "cmd.aspx",
        "ntdaddy.asp",
        "ntdaddy.aspx",
        "ntdaddy.mspx",
        "cmd.mspx",
        "shell.asp",
        "zehir4.asp",
        "rhtools.asp",
        "fso.asp",
        "shell.aspx",
        "zehir4.aspx",
        "rhtools.aspx",
        "fso.aspx",
        "shell.mspx",
        "zehir4.mspx",
        "rhtools.mspx",
        "fso.mspx",
        "kshell.asp",
        "aspydrv.asp",
        "kacak.asp",
        "kshell.aspx",
        "aspydrv.aspx",
        "kacak.aspx",
        "kshell.mspx",
        "aspydrv.mspx",
        "kacak.mspx",
        "cmd.cfm",
        "cfexec.cfm",
        "shell.cfm",
        "shell.do",
        "shell.nsf",
        "shell.d2w",
        "shell.GPL",
        "shell.show",
        "shell.py",
        "cmd.do",
        "cmd.nsf",
        "cmd.d2w",
        "cmd.GPL",
        "cmd.show",
        "cmd.py",
        "cmd.c",
        "exploit.c",
        "0wn3d.c",
        "cmd.sh",
        "cmd.js",
        "shell.js",
        "list.sh",
        "up.sh",
        "nc.exe",
        "netcat.exe",
        "socat.exe",
        "cmd.pl",
        "wild_steve_here.exe", 
        "jews_did_wtc.exe", 
        "KMS.exe", 
        "fud.exe",                  
        "windongs.exe", 
        "dragondildo.exe", 
        "wc.exe", 
        "windos.exe",                 
        "butt.exe", 
        "wincap.exe", 
        "911.exe", 
        "zzz.exe", 
        "newcrypt.exe",                    
        "1.cfm", 
        "cffm.cfm", 
        "h.cfm", 
        "help.cfm", 
        "i.cfm",                    
        "fusebox.cfm", 
        "adss.cfm", 
        "trip.jar", 
        "h9.cfm", 
        "r.cfm",                           
        "info.cfm", 
        "s.cfm", 
        "testcfmtask.cfm" 
    ]
};

module.exports = {
    IMPACT_LEVEL: IMPACT_LEVEL,
    MALWARE_TYPE: MALWARE_TYPE,
    db: db
};