"use strict";

var IMPACT_LEVEL = {
    LOW: 0,
    MEDIUM: 1,
    HIGH: 2
};

var MALWARE_TYPE = {
    WEB_SHELL: 0,
    VIRUS: 1,
    MALICIOUS_CODE: 2
};

var db = {
    re: [
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /r0nin/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /m0rtix/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /upl0ad/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /r57shell/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /cFaTaLisTiCz_Fx/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Tukulesto/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /99shell/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /shellbot/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /phpshell/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /void\.ru/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /phpremoteview/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /directmail/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /bash_history/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /brute *force/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /multiviews/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /cwings/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /vandal/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /bitchx/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /eggdrop/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /guardservices/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /psybnc/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /dalnet/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /undernet/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /vulnscan/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /spymeta/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /raslan58/ig },
        { type: MALWARE_TYPE.WEB_SHELL, impact: IMPACT_LEVEL.HIGH, expr: /Webshell/ig },
    
    ],
    path: [
        "php-backdoor.php",
        "simple-backdoor.php",
        "cmd.php",
        "phpshell.php",
        "NCC-Shell.php",
        "mysql.php",
        "mysql_tool.php",
        "gfs_sh.php",
        "iMHaPFtp.php",
        "ironshell.php",
        "lamashell.php",
        "load_shell.php",
        "matamu.php",
        "c99_w4cking.php",
        "Crystal.php",
        "ctt_sh.php",
        "cybershell.php",
        "Dx.php",
        "c99_PSych0.php",
        "c99_madnet.php",
        "c99_locus7s.php",
        "c99.php",
        "accept_language.php",
        "rootshell.php",
        "ru24_post_sh.php",
        "zacosmall.php",
        "pws.php",
        "r57.php",
        "r57_iFX.php",
        "r57_kartal.php",
        "r57_Mohajer22.php",
        "pHpINJ.php",
        "PHPJackal.php",
        "PHPRemoteView.php",
        "Private-i3lue.php",
        "PHANTASMA.php",
        "nstview.php",
        "nshell.php",
        "NetworkFileManagerPHP.php",
        "simple_cmd.php",
        "Uploader.php",
        "php-include-w-shell.php",
        "backupsql.php",
        "myshell.php",
        "c99shell.php",
        "c100.php",
        "c100shell.php",
        "locus7s.php",
        "locus.php",
        "safe0ver.php",
        "stresbypass.php",
        "ekin0x.php",
        "liz0zim.php",
        "erne.php",
        "spybypass.php",
        "phpbypass.php",
        "sosyete.php",
        "remview.php",
        "zaco.php",
        "nst.php",
        "heykir.php",
        "simattacker.php",
        "avent.php",
        "fatal.php",
        "dx.php",
        "goonshell.php",
        "safemod.php",
        "unreal.php",
        "w4k.php",
        "winshell.php",
        "mysql2.php",
        "sql.php",
        "jackal.php",
        "dc.php",
        "w4cking.php",
        "x.php",
        "xx.php",
        "xxx.php",
        "w3k.php",
        "h4x.php",
        "h4x0r.php",
        "l33t.php",
        "cod3r.php",
        "cod3rzshell.php",
        "cod3rz.php",
        "locus.php",
        "locu.php",
        "jsback.php",
        "worm.php",
        "simp-worm_sys.p5.php",
        "owned.php",
        "0wn3d.php",
        "perlcmd.cgi",
        "cmd.pl",
        "shell.pl",
        "cmd.cgi",
        "shell.cgi",
        "jsp-reverse.jsp",
        "cmdjsp.jsp",
        "cmd.jsp",
        "cmd_win32.jsp",
        "JspWebshell.jsp",
        "JspWebshell1.2.jsp",
        "shell.jsp",
        "jsp-reverse.jspx",
        "cmdjsp.jspx",
        "cmd.jspx",
        "cmd_win32.jspx",
        "JspWebshell.jspx",
        "JspWebshell1.2.jspx",
        "shell.jspx",
        "browser.jsp",
        "cmd_win32.jsp",
        "CmdServlet",
        "cmdServlet",
        "servlet/CmdServlet",
        "servlet/cmdServlet",
        "ListServlet",
        "UpServlet",
        "up_win32.jsp",
        "cmd.asp",
        "cmdasp.aspx",
        "cmdasp.asp",
        "cmd-asp-5.1.asp",
        "cmd.aspx",
        "ntdaddy.asp",
        "ntdaddy.aspx",
        "ntdaddy.mspx",
        "cmd.mspx",
        "shell.asp",
        "zehir4.asp",
        "rhtools.asp",
        "fso.asp",
        "shell.aspx",
        "zehir4.aspx",
        "rhtools.aspx",
        "fso.aspx",
        "shell.mspx",
        "zehir4.mspx",
        "rhtools.mspx",
        "fso.mspx",
        "kshell.asp",
        "aspydrv.asp",
        "kacak.asp",
        "kshell.aspx",
        "aspydrv.aspx",
        "kacak.aspx",
        "kshell.mspx",
        "aspydrv.mspx",
        "kacak.mspx",
        "cmd.cfm",
        "cfexec.cfm",
        "shell.cfm",
        "shell.do",
        "shell.nsf",
        "shell.d2w",
        "shell.GPL",
        "shell.show",
        "shell.py",
        "cmd.do",
        "cmd.nsf",
        "cmd.d2w",
        "cmd.GPL",
        "cmd.show",
        "cmd.py",
        "cmd.c",
        "exploit.c",
        "0wn3d.c",
        "cmd.sh",
        "cmd.js",
        "shell.js",
        "list.sh",
        "up.sh",
        "nc.exe",
        "netcat.exe",
        "socat.exe",
        "cmd.pl",
        "wild_steve_here.exe", 
        "jews_did_wtc.exe", 
        "KMS.exe", 
        "fud.exe",                  
        "windongs.exe", 
        "dragondildo.exe", 
        "wc.exe", 
        "windos.exe",                 
        "butt.exe", 
        "wincap.exe", 
        "911.exe", 
        "zzz.exe", 
        "newcrypt.exe",                    
        "1.cfm", 
        "cffm.cfm", 
        "h.cfm", 
        "help.cfm", 
        "i.cfm",                    
        "fusebox.cfm", 
        "adss.cfm", 
        "trip.jar", 
        "h9.cfm", 
        "r.cfm",                           
        "info.cfm", 
        "s.cfm", 
        "testcfmtask.cfm" 
    ]
};

module.exports = {
    IMPACT_LEVEL: IMPACT_LEVEL,
    MALWARE_TYPE: MALWARE_TYPE,
    db: db
};